//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContact
    {
        public string Entreprise { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Fonction { get; set; }
        public string Telephone { get; set; }
        public string Projet { get; set; }
        public string Activite { get; set; }
        public int IdClient { get; set; }
        public int IdContact { get; set; }
    
        public virtual TClient TClient { get; set; }
    }
}
